set number
syntax enable
set backspace=indent,start,eol
set list
set listchars=eol:¬,tab:>·,trail:~,extends:>,precedes:<,space:.
set incsearch
set hlsearch
set autoindent
set nowrap
set expandtab
set shiftwidth=4
set softtabstop=4
set tabstop=4
set laststatus=2
set cursorline
set autoindent
set mouse=a
